### PR TITLE
WRLDBAEMS-275: Minor fixes

### PR DESCRIPTION
**Pull request by adobe-rpal**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [WRLDBAEMS-275](https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-275)

Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/ext/en/who-we-are
- After: https://WRLDBAEMS-275-fixes--world-bank--aemsites.aem.live/ext/en/who-we-are

### CODE REVIEW

**Comment by thomsebastin** [comment]
@adobe-rpal  Please update the link to point to who we are.

**Review by mkbansal1 — CHANGES_REQUESTED** [review]
@adobe-rpal Arrows are missing in small view ports (tab & mobile)
image

**Comment by adobe-rpal** [comment]
Arrows are not required for mobile & tablet view, but in desktop.

**Comment by adobe-rpal** [comment]
> @adobe-rpal Please update the link to point to who we are.

Done

**Comment by adobe-rpal** [comment]
> @adobe-rpal Arrows are missing in small view ports (tab & mobile) image

Arrows are not required for mobile & tablet view, but in desktop.

**Review by mkbansal1 — APPROVED** [review]

**Pull request merged**
