### PR TITLE
Home page design variables

### PR DESCRIPTION
**Pull request by singhpritam18**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Pending Items
**Explore Cards
Latest From World Bank
Footer** 

Test URLs:
- Before: https://main--world-bank--aemsites.aem.live/
- After: https://homePageDesignVariables--world-bank--aemsites.aem.live/

### CODE REVIEW

**Comment by arjun87743** [comment]
Screenshot 2024-09-26 170946
Please check this

**Comment by arjun87743** [comment]
s2
Please check

**Review by mkbansal1 — CHANGES_REQUESTED** [review]
@singhpritam18 i noticed many rules are removed in your changes, is this tested properly?

**Comment by singhpritam18** [comment]
> Screenshot 2024-09-26 170946 Please check this

Done. Please check

**Comment by singhpritam18** [comment]
> @singhpritam18 i noticed many rules are removed in your changes, is this tested properly?

Yes, I have only removed the rules which are related to line-height and padding which was hard coded. As after giving the padding as per spacing variable there's no need to have rules specific to device width. Rest, I have updated the old variables with new one

**Review by arjun87743 — APPROVED** [review]
Working fine for signup and explore cards

**Comment by mkbansal1** [comment]
@singhpritam18 Resolve conflicts and merge your PR

**Pull request merged**
