### PR TITLE
issue#47 teaser component

### PR DESCRIPTION
**Pull request by mdickson-adbe**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix#: https://adobe-acs-group.atlassian.net/browse/WRLDBAEMS-47

Desktop:
image

Tablet:
image

Mobile:
image

Test URLs:
- Before: https://main--world-bank--aemsites.hlx.live/
- After: https://47-teaser--world-bank--aemsites.hlx.live/en/drafts/michael/teaser

Author URL: https://author-p136806-e1403562.adobeaemcloud.com/content/world-bank/global/en/drafts/michael/teaser.html?ref=47-teaser

### CODE REVIEW

**Comment by mdickson-adbe** [comment]
RE: build failing, I don't know how to resolve xwalk's issue with such a deep component model while still meeting all of the requirements of the ticket, but happy to adjust pending guidance.

**Comment by thomsebastin** [comment]
@mdickson-adbe This is how it looks on Mobile. Something doesn't feel right. Could you please check this?
Screenshot 2024-08-29 at 11 47 23 AM

**Comment by thomsebastin** [comment]
@mdickson-adbe Could you please fix the conflicts?

**Comment by mdickson-adbe** [comment]
Merge conflicts resolved

**Review by thomsebastin — APPROVED** [review]

**Pull request merged**
